schema_version = "1.0.0"
id = "crashxform"
version = "1.2.2"
name = "CrashXform"
tagline = "Tools for working with models and scenery from original Crash Bandicoot video game trilogy"
maintainer = "Airumu"
type = "add-on"
website = "https://github.com/airumu/Blender_CrashXform"
tags = ["Import-Export", "Material", "Mesh", "Node"]
blender_version_min = "4.2.0"
license = ["SPDX:GPL-3.0-or-later"]